PROJECT:
  name: 'MFNeXt'
  save_path: './work_dirs/MFLIT6/'
# MFLIT1 final model; MFLIT only CFM MFLIT2 CFM + FFM MFLIT3 no FAM MFLIT5 ResNet MFLIT6 SwinTransformer
TRAIN_DATASET:
  phase: 'train'
  patch_size: 256
  root_dir: './datasets/Dataset/'
  sensors: ['Far', 'Near', 'focus_map', 'Boundary']
  channels: 3
  input_size: 256
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]

TRAIN:
  batch_size: 24
  max_epoch: 50
  lr: 0.00001
  gamma: 0.5
  milestones: [10, 20, 40, 60, 80]
  opt: AdamW #RMSprop
  loss_func: ['Loss_CFM', 'Loss_FM', 'Loss_Bound']
  val_interval: 1, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 150, 160, 170, 180, 190, 200
  valid_interval: 1, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 150, 160, 170, 180, 190, 200
  debug_interval: 5000
  resume: None
  loss_weights: [ 1, 1, 1]
  weight_decay: 0.01
  EPS: 0.00000001
  BETAS: [0.9, 0.999]
  LR_SCHEDULER: poly
  MIN_LR: 0.00000001
  WARMUP_LR: 0.0001
  WARMUP_EPOCHS: 5
  DECAY_RATE: 0.01
  DECAY_EPOCHS: 10

TEST_DATASET:
  root_dir: './datasets/test/'
  phase: 'test'
  sensors: [ 'Far', 'Near' ]
  channels: 3
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]

TEST:
  batch_size: 1
  weight_path: './work_dirs/MFLIT1/MFNeXt/model_20.pth'
  save_path: './datasets/result/MFLIT6/'

MODEL:
  model_name: 'MFNeXt'
  phase: 'Train'
  input_channels: 3
  out_channels: 3
  input_sensors: ['Far', 'Near', 'focus_map', 'Boundary']
  input_size: 256
#  coder_layers: 4
#  decoder_layers: 4
#  fuse_scheme: 0
